### ISSUE TITLE
OSError: [Errno 5] Input/output error[BUG] - in example project hello-pt-tb

### ISSUE THREAD

**Issue by gonzaq94** [NVIDIA/NVFlare#1080]
**Describe the bug**
OSError: [Errno 5] Input/output error is raised when trying to execute one of the example applications of the project (hello-pt-tb). The server, two clients, and the admin are correctly launched and connected, but the training fails.

**To Reproduce**
1. Use the nvflare provision tool to create the files of the server, two clients and the admin "nvflare provision -p project.yml"
2.  Copy the folder "examples/hello-pt-tb" to the the transfer folder of the admin, created by the provision tool ("workspace/example_project/prod_03/admin@nvidia.com/transfer")
3. Launch the server, clients and admin. The clients and admin are successfully connected to the server.
4. In the admin prompt, launch the application by tapping "submit_job hello-pt-tb"
5. The application is launched (the admin prompt returns the message "Submitted job: 80e42c2f-dc9f-41f0-883c-797bdd300d0c
Done [33593 usecs] 2022-10-21 10:16:37.190783")
6. The application is interrupted with the OSError: [Errno 5] Input/output error[BUG]

**Expected behavior**
Training on CIFAR data should be launched.

**Screenshots**

***log.txt file of site-1***
2022-10-20 15:54:22,595 - worker_process - INFO - Worker_process started.
2022-10-20 15:54:35,127 - LearnerExecutor - ERROR - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: learner initialize exception: [Errno 5] Input/output error
2022-10-20 15:54:35,136 - LearnerExecutor - ERROR - Traceback (most recent call last):
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 156, in download_url
    _urlretrieve(url, fpath)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 50, in _urlretrieve
    _save_response_content(iter(lambda: response.read(chunk_size), b""), filename, length=response.length)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 45, in _save_response_content
    pbar.update(len(chunk))
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torch/hub.py", line 43, in update
    sys.stderr.flush()
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/github/NVFlare/nvflare/app_common/executors/learner_executor.py", line 68, in initialize
    self.learner.initialize(engine.get_all_components(), fl_ctx)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/gitlab/NVFlare-test/workspace/example_project/prod_03/site-1/cd6ee7e4-25ab-4b70-a6e7-afe01d915d63/app_site-1/custom/pt_learner.py", line 88, in initialize
    self.train_dataset = CIFAR10(root=self.data_path, transform=transforms, download=True, train=True)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 141, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 446, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 161, in download_url
    _urlretrieve(url, fpath)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 50, in _urlretrieve
    _save_response_content(iter(lambda: response.read(chunk_size), b""), filename, length=response.length)
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 45, in _save_response_content
    pbar.update(len(chunk))
  File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/nvflare-2.2-env/lib/python3.7/site-packages/torch/hub.py", line 43, in update
    sys.stderr.flush()
OSError: [Errno 5] Input/output error

2022-10-20 15:54:35,138 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: client runner started
2022-10-20 15:54:35,179 - Communicator - INFO - Received from example_project server  (371 Bytes). getTask time: 0.023667097091674805 seconds
2022-10-20 15:54:35,241 - FederatedClient - INFO - pull_task completed. Task name:__end_run__ Status:True 
2022-10-20 15:54:35,243 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63, peer=example_project, peer_run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: server asked to end the run
2022-10-20 15:54:35,344 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: run method requests end run events sequence
2022-10-20 15:54:36,724 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: received aux request from Server to end current RUN
2022-10-20 15:54:36,727 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: ABORT (RUN) command received
2022-10-20 15:54:36,728 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: ABORT (RUN) requests end run events sequence
2022-10-20 15:54:37,347 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: ABOUT_TO_END_RUN fired
2022-10-20 15:54:37,641 - ClientRunner - INFO - [identity=site-1, run=cd6ee7e4-25ab-4b70-a6e7-afe01d915d63]: END_RUN fired
2022-10-20 15:54:37,643 - FederatedClient - INFO - Shutting down client: site-1

**Desktop**
 - OS: 18.04 (Ubuntu 18.04.3 LTS)
 - Python Version 3.7.5
 - NVFlare Version 2.2.1rc8+1.g8ff2b3d

**Additional context**

***When the clients are launched, the following message is shown. I am not sure if both errors are related***
E1021 11:06:52.365657173    8683 http_proxy.cc:79]           cannot parse value of 'http_proxy' env var. Error: OK

***project.yml file for provision (the server FQDN has been replaced by 'server.com') -  special characters have been backslashed to avoid being interpreted***
api_version: 3
name: example_project
description: NVIDIA FLARE sample project yaml file

participants:
  \# change example.com to the FQDN of the server
  \- name: server.com
    type: server
    org: nvidia
    fed_learn_port: 8002
    admin_port: 8003
  \- name: site-1
    type: client
    org: nvidia
  \- name: site-2
    type: client
    org: nvidia
  \- name: admin@nvidia.com
    type: admin
    org: nvidia
    role: project_admin

\# The same methods in all builders are called in their order defined in builders section
builders:
  \- path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml
  \- path: nvflare.lighter.impl.template.TemplateBuilder
  \- path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      \# config_folder can be set to inform NVIDIA FLARE where to get configuration
      config_folder: config

      \# app_validator is used to verify if uploaded app has proper structures
      \# if not set, no app_validator is included in fed_server.json
      \# app_validator: PATH_TO_YOUR_OWN_APP_VALIDATOR

      \# when docker_image is set to a docker image name, docker.sh will be generated on server/client/admin
      \# docker_image:

      \# download_job_url is set to http://download.server.com/ as default in fed_server.json.  You can override this
      \# to different url.
      \# download_job_url: http://download.server.com/

      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        \# if overseer_exists is true, args here are ignored.  Provisioning
        \#   tool will fill role, name and other local parameters automatically.
        \# if overseer_exists is false, args in this section will be used and the sp_end_point
        \# must match the server defined above in the format of SERVER_NAME:FL_PORT:ADMIN_PORT
        \# 
        overseer_exists: false
        args:
          sp_end_point: server.com:8002:8003

  \- path: nvflare.lighter.impl.cert.CertBuilder
  \- path: nvflare.lighter.impl.signature.SignatureBuilder"

**Comment by YuanTingHsieh** [comment]
Hi @gonzaq94 ,

Thanks for your interest and detailed information.


From the log you provided, 
The following line is failing:

```
File "/net/frbucx05nvsr01n/vol/static02/tomo-database/bcare/accounts/quintana_g/gitlab/NVFlare-test/workspace/example_project/prod_03/site-1/cd6ee7e4-25ab-4b70-a6e7-afe01d915d63/app_site-1/custom/pt_learner.py", line 88, in initialize
self.train_dataset = CIFAR10(root=self.data_path, transform=transforms, download=True, train=True)
```

(code is this line: https://github.com/NVIDIA/NVFlare/blob/dev/examples/hello-pt-tb/app/custom/pt_learner.py#L88 )

By default, "~/data" is used. (https://github.com/NVIDIA/NVFlare/blob/dev/examples/hello-pt-tb/app/custom/pt_learner.py#L44)

This means torchvision will try to download the CIFAR10 data into "~/data".

I would suspect your example is failing due to some permission error for the "~/data" folder.
I will suggest the following actions:

1. Make sure all your client site has installed `torchvision` (and required libraries for this job)
2. Make sure this line runs in all your client site: `python3 -c "from torchvision.datasets import CIFAR10; CIFAR10(root='~/data',download=True, train=True)"`

You should see something similar like this

```
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /home/yuantingh/data/cifar-10-python.tar.gz
100.0%
Extracting /home/yuantingh/data/cifar-10-python.tar.gz to /home/yuantingh/data
```

Or

```
Files already downloaded and verified
```

**Comment by holgerroth** [comment]
@gonzaq94 did this solve your issue?

**Comment by gonzaq94** [comment]
Hi @holgerroth @YuanTingHsieh 

Thank you very much for the answer.

Unfortunately, this did not solve the issue.

However, I managed to solve the issue for my personal project (not for the hello-pt-tb project) by running different sites in different machines or workstations (before, I was testing with two clients/sites in the same physical machine).

Does NvFlare support running two or more clients in the same physical machine ? Do you think this could be the reason behind this issue ?

Best,

Gonzalo

**Comment by YuanTingHsieh** [comment]
Hi @gonzaq94 ,

Thanks for the update.

Does NvFlare support running two or more clients in the same physical machine?
=> The anwser is Yes.

Do you think this could be the reason behind this bug?
=> The anwser is Yes.

NVFlare does support running 2 or more clients in the same physical machine.

However, for this hello-pt example, if you are running 2 or more clients in the same physical machine WITHOUT downloading the data first.
When the job is running, there is a possibility that both site-1 and site-2 started the hello-pt app and try to download the data and unzip it to the same location at the same time.
This racing condition will cause the data to be corrupted.

To fix this, to run multiple clients in the same physical machine, please make sure your data is downloaded first before you submit the job into NVFlare system.

Hope this helps.

Thanks,
Yuan-Ting

**Comment by holgerroth** [comment]
@gonzaq94, you can have a look at the cifar-10 example. Here we actually use a handler on the server-side to do the data download and splitting before the clients start training https://github.com/NVIDIA/NVFlare/blob/ce306e04700b448f7a8ad3af8e59c06bcc9dc1b9/examples/cifar10/cifar10-sim/job_configs/cifar10_fedavg/cifar10_fedavg/config/config_fed_server.json#L15. 

This should reduce the likelihood of a racing condition but it assumes that server and clients access the same data directory (for simulation purpose).

**Comment by holgerroth** [comment]
@gonzaq94 are you still experiencing this issue?
