### ISSUE TITLE
XGBoostError - in the example of Histogram-based Federated Learning for XGBoost

### ISSUE THREAD

**Issue by EZlzh** [NVIDIA/NVFlare#1160]
**Describe the bug**
xgboost.core.XGBoostError: XGBoost needs to be built with the federated learning plugin enabled in order to use this module

**To Reproduce**
1. Go to the path of 'https://github.com/NVIDIA/NVFlare/tree/main/examples/xgboost/histogram-based'
2. Run federated experiments with simulator locally './run_experiment_simulator.sh'
3. See error.

**Expected behavior**
Run federated experiments with simulator locally should be normally executed.

**Screenshots**
Process Process-2:1:
Traceback (most recent call last):
  File ".../lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File ".../lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File ".../lib/python3.8/site-packages/xgboost/federated.py", line 42, in run_federated_server
    raise XGBoostError(
xgboost.core.XGBoostError: XGBoost needs to be built with the federated learning plugin enabled in order to use this module

**Desktop (please complete the following information):**
 - OS: macOS Ventura Version 13.0.1
 - Python Version 3.8.13
 - NVFlare Version 2.2.1

**Additional context**
When I ran the histogram-based learning for XGBoost, it worked fine with the centralized experiment, but it raised the XGBoostError when I executed the following command.
```
bash run_experiment_simulator.sh
```
In addition, the `requirements.txt` file of histogram-based learning is incomplete compared to that of tree-based learning for XGBoost.
Thanks a lot in advance for your team's great support!

**Comment by EZlzh** [comment]
> I just repeat your steps, I did not see the error your reported. did you install the xgboost dependency as instructed in readme ? `pip install -r requirements.txt` https://github.com/NVIDIA/NVFlare/tree/main/examples/xgboost/histogram-based

Thank you for your kind help! I tried this method but it didn't work. Later I realized it might be the incompatibility with the Ventura system, since I repeated it successfully on another machine, but with "insecured federated server" prompted.
