### ISSUE TITLE
[BUG] TypeError: 'str' object is not callable in XGBoost examples

### ISSUE THREAD

**Issue by Jeffwan** [NVIDIA/NVFlare#1180]
**Describe the bug**

I follow the instruction and run XGBoost example but meet a problem like beflow

**To Reproduce**
https://github.com/NVIDIA/NVFlare/tree/dev/examples/xgboost/histogram-based

**Expected behavior**

logs: 
```
2022-12-02 20:24:24,400 - FedXGBHistogramHiggsExecutor - INFO - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=be55e98c-99b8-
419f-b16d-0b86a9074be7]: Using xgb params: {'max_depth': 8, 'eta': 0.1, 'objective': 'binary:logistic', 'eval_metric': 'auc', 'tree_method': 'hist', 'nthread': 16}
2022-12-02 20:24:24,426 - root - ERROR - Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.8/site-packages/nvflare/app_opt/xgboost/histogram_based/executor.py", line 208, in train
    bst = self.xgb_train(params)
  File "/home/tiger/.local/lib/python3.8/site-packages/nvflare/app_opt/xgboost/histogram_based/executor.py", line 90, in xgb_train
    bst = xgb.train(
  File "/home/tiger/.local/lib/python3.8/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
  File "/home/tiger/.local/lib/python3.8/site-packages/xgboost/training.py", line 185, in train
    bst.update(dtrain, i, obj)
  File "/home/tiger/.local/lib/python3.8/site-packages/xgboost/core.py", line 1923, in update
    grad, hess = fobj(pred, dtrain)
TypeError: 'str' object is not callable

2022-12-02 20:24:24,426 - FedXGBHistogramHiggsExecutor - ERROR - [identity=site-2, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=be55e98c-99b8
-419f-b16d-0b86a9074be7]: Exception happens when running xgb train: 'str' object is not callable
```

`squared_log` is passed as value of obj but it's used to `fobj(pred, dtrain)`

https://github.com/NVIDIA/NVFlare/blob/7dac9945dfdef3ffd1c1e023dea5f5258a74c3f9/nvflare/app_opt/xgboost/histogram_based/executor.py#L90-L99

![image](https://user-images.githubusercontent.com/4739316/205732333-7b5aa08f-0cd3-449c-9381-c7af23778d67.png)

xgboost/core.py#1923

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 16.04]
 - Python Version [e.g. 3.8]
 - NVFlare Version [e.g. 2.1]

**Additional context**

**Comment by Jeffwan** [comment]
I notice centralized training doesn't pass this `obj`, could I just remove it?

**Comment by pygabc1** [comment]
Hi, I tried with the example application as well, It seems the problem still exists in 2.2 version and dev version. Do you want to follow up with the issue? Thanks!
