### ISSUE TITLE
[BUG] Cannot find component class "InitializeGlobalWeights"

### ISSUE THREAD

**Issue by pygabc1** [NVIDIA/NVFlare#1310]
Hi, I got an error, which is [Cannot find component class "InitializeGlobalWeights"],  when I run hello-pt example. I would appreciate for any suggestion.

> 2023-02-06 20:00:29,202 - SimulatorRunner - ERROR - FL server execution exception: Config error in ['/NvidiaFlare/github/WorkSpaceHello/workspace/simulate_job/app_server/config/config_fed_server.json']: Error processing ['/NvidiaFlare/github/WorkSpaceHello/workspace/simulate_job/app_server/config/config_fed_server.json'] in JSON element {'id': 'pre_train', 'name': 'InitializeGlobalWeights', 'args': {'task_name': 'get_weights'}}: path: workflows.#1, exception: Cannot find component class "InitializeGlobalWeights"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nvflare/fuel/utils/json_scanner.py", line 96, in _do_scan
    node.processor.process_element(node)
  File "/usr/local/lib/python3.8/site-packages/nvflare/private/json_configer.py", line 122, in process_element
    self.process_config_element(self.config_ctx, node)
  File "/usr/local/lib/python3.8/site-packages/nvflare/private/fed/server/server_json_config.py", line 98, in process_config_element
    workflow = self.build_component(element)
  File "/usr/local/lib/python3.8/site-packages/nvflare/private/fed/server/server_json_config.py", line 128, in build_component
    t = super().build_component(config_dict)
  File "/usr/local/lib/python3.8/site-packages/nvflare/fuel/utils/component_builder.py", line 50, in build_component
    class_path = self.get_class_path(config_dict)
  File "/usr/local/lib/python3.8/site-packages/nvflare/fuel/utils/component_builder.py", line 85, in get_class_path
    raise ConfigError('Cannot find component class "{}"'.format(class_name))
nvflare.fuel.common.excepts.ConfigError: Cannot find component class "InitializeGlobalWeights"

**Comment by YuanTingHsieh** [comment]
Hello @pygabc1 thanks for the interest and raising the question.

I am assuming you are using NVFlare 2.2.X version.

You need to refer to the example codes here: https://github.com/NVIDIA/NVFlare/tree/2.2/examples

Instead of getting examples on the default branch (dev) branch.

**Comment by pygabc1** [comment]
I didn't know it has several version. 2.2 version does not have any problem. Thank you.
