### ISSUE TITLE
[BUG] HEModelEncryptor error against Vertical FL

### ISSUE THREAD

**Issue by shawndengucf** [NVIDIA/NVFlare#1924]
**Describe the bug**
I setup a VFL experiment following the cifar10-splitnn example, with my own tabular data as input, and it worked. Based on that, I added the HEModelEncryptor but ran into a TypeError as below.

**To Reproduce**
I setup the Homomorphic Encryption (HE) filters in the job configuration json files for all clients (but not the server) as below:
```
  "task_result_filters": [
    {
      "tasks": [
        "train"
      ],
      "filters": [
        {
          "name": "HEModelEncryptor",
          "args": {
            "weigh_by_local_iter": true
          }
        }
      ]
    },
    {
      "tasks": [
        "submit_model"
      ],
      "filters": [
        {
          "name": "HEModelEncryptor",
          "args": {
            "weigh_by_local_iter": false
          }
        }
      ]
    }
  ],
  "task_data_filters": [
    {
      "tasks": [
        "train",
        "validate"
      ],
      "filters": [
        {
          "name": "HEModelDecryptor",
          "args": {
          }
        }
      ]
    }
  ]
```
When I submit my job with SimulatorRunner, the error occur, see below.

**Expected behavior**
The training completed with no error.

**Screenshots**
Below is the error message:
```
2023-08-09 15:11:58,526 - HEModelEncryptor - ERROR - [identity=site-2, run=simulate_job]: Exception when handling event "_start_run": TypeError: deserialize(): incompatible function arguments. The following argument types are supported:
    1. (buffer: str, n_threads: Optional[int] = 10) -> _tenseal_cpp.TenSEALContext

Invoked with: None
2023-08-09 15:11:58,526 - HEModelEncryptor - ERROR - Traceback (most recent call last):
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/private/event.py", line 61, in fire_event
    h.handle_event(event, ctx)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/app_opt/he/model_encryptor.py", line 105, in handle_event
    self.tenseal_context = load_tenseal_context_from_workspace(self.tenseal_context_file, fl_ctx)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/app_opt/he/homomorphic_encrypt.py", line 43, in load_tenseal_context_from_workspace
    context = ts.context_from(data)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/tenseal/__init__.py", line 71, in context_from
    return Context.load(data, n_threads)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/tenseal/enc_context.py", line 170, in load
    return cls._wrap(ts._ts_cpp.TenSEALContext.deserialize(data))
TypeError: deserialize(): incompatible function arguments. The following argument types are supported:
    1. (buffer: str, n_threads: Optional[int] = 10) -> _tenseal_cpp.TenSEALContext

Invoked with: None
```

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1 with Apple M1 Max Chip
 - Python Version: 3.9.17
 - NVFlare Version: 2.3.2
 - tenseal: 0.3.0

**Additional context**
I installed an older version of `tenseal` because the latest version doesn't support Apple M1 Chip.

Thank you!

**Comment by holgerroth** [comment]
Hi @shawndengucf , you need to create the tenseal context files that include the encryption keys. For that, you would need to run the secure provisioning: https://github.com/NVIDIA/NVFlare/tree/main/examples/advanced/cifar10/cifar10-real-world#31-secure-fl-workspace. If you want to use them in the simulator, you can copy them to some permanent place and specify the filename in the [HEModelEncryptor](https://github.com/NVIDIA/NVFlare/blob/3cfb12ae31bc68cc778b5eea906f352e25f52620/nvflare/app_opt/he/model_encryptor.py#L36).

However, you will run into other issues with split learning. We don't support computing the loss function with HE at the moment. In the linked horizontal FL with CIFAR-10, HE is used for aggregation on the server. Is encrypted split learning something you are interested in? Or is it more about end-to-end encryption between the clients? We might have a more efficient solution for that in the next release, cc @yanchengnv.

**Comment by shawndengucf** [comment]
Thanks, @holgerroth ! It's really helpful. I created the `secure_workspace` and copied the whole folder to my project folder and specified the `tenseal_context_file` for `HEModelEncryptor`. However, the error persisted and I noticed that `SecurityContentService` doesn't get a chance to initial the `security_content_manager` if I submit the job with the simulator, see `load_tenseal_context_from_workspace` from `homomorphic_encrypt.py`.

I made it work by editing the function to below:
```
def load_tenseal_context_from_workspace(ctx_file_name: str, fl_ctx: FLContext):
    """Loads homomorphic encryption (HE) context from TenSEAL (https://github.com/OpenMined/TenSEAL) containing encryption keys and parameters.

    Args:
        ctx_file_name: filepath of TensSEAL context file
        fl_ctx: FL context

    Returns:
        TenSEAL context

    """
    is_secure_mode = fl_ctx.get_prop(FLContextKey.SECURE_MODE, True)
    if ctx_file_name != "client_context.tenseal":
        ssc = SecurityContentService()
        ssc.initialize(os.path.dirname(ctx_file_name))
        data, rc = ssc.load_content(ctx_file_name)
    else:
        data, rc = SecurityContentService.load_content(ctx_file_name)

    bad_rcs = [LoadResult.INVALID_CONTENT, LoadResult.NO_SUCH_CONTENT]
    if is_secure_mode:
        bad_rcs.extend([LoadResult.INVALID_SIGNATURE, LoadResult.NOT_SIGNED])

    if rc in bad_rcs:
        raise ValueError("Cannot load tenseal_context {}: {}".format(ctx_file_name, rc))

    context = ts.context_from(data)
    return context
```

With that error fixed, I bumped into the error below after the encryption:
```
-9972-4e44-af60-56a53c330eb2]: Encrypting vars 16 of 16: batchnorm2.num_batches_tracked with 1 values
2023-08-24 14:22:41,682 - HEModelEncryptor - INFO - [identity=site-1, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=2183f98a-9972-4e44-af60-56a53c330eb2]: Encryption time for 45891 of 45891 params (encrypted value range [-3.9569482803344727, 980.0]) 0.05233168601989746 seconds.
2023-08-24 14:22:41,683 - HEModelEncryptor - INFO - [identity=site-1, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=2183f98a-9972-4e44-af60-56a53c330eb2]: 16 of 16 layers encrypted
2023-08-24 14:22:41,683 - ClientRunner - INFO - [identity=site-1, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=2183f98a-9972-4e44-af60-56a53c330eb2]: finished processing task
2023-08-24 14:22:41,684 - FederatedClient - INFO - Starting to push execute result.
2023-08-24 14:22:41,888 - Cell - ERROR - [ME=server.simulate_job O=site-1.simulate_job D=server.simulate_job F=server T=server.simulate_job CH=server_command TP=submit_update] exception from CB execute_command: TypeError: Unknown type tenseal.tensors.ckksvector.CKKSVector, caused by mismatching decomposers
2023-08-24 14:22:41,888 - Cell - ERROR - Traceback (most recent call last):
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/fuel/f3/cellnet/cell.py", line 1437, in _try_cb
    return cb(message, *args, **kwargs)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/private/fed/server/server_command_agent.py", line 60, in execute_command
    data = fobs.loads(request.payload)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/fuel/utils/fobs/fobs.py", line 249, in deserialize
    return msgpack.unpackb(data, object_hook=_fobs_unpacker, **kwargs)
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/fuel/utils/fobs/fobs.py", line 202, in _fobs_unpacker
    raise TypeError(f"Unknown type {type_name}, caused by mismatching decomposers")
TypeError: Unknown type tenseal.tensors.ckksvector.CKKSVector, caused by mismatching decomposers
```

I was wondering if you can share some ideas about how to solve it.

Below is the way I setup the HEModelEncryptor:
```
  "task_result_filters": [
    {
      "tasks": [
        "train"
      ],
      "filters": [
        {
          "name": "HEModelEncryptor",
          "args": {
            "weigh_by_local_iter": true,
            "tenseal_context_file": "/path/to/my/client_context.tenseal"
          }
        }
      ]
    },
    {
      "tasks": [
        "submit_model"
      ],
      "filters": [
        {
          "name": "HEModelEncryptor",
          "args": {
            "weigh_by_local_iter": false,
            "tenseal_context_file": "/path/to/my/client_context.tenseal"
          }
        }
      ]
    }
  ],
  "task_data_filters": [
    {
      "tasks": [
        "train",
        "validate"
      ],
      "filters": [
        {
          "name": "HEModelDecryptor",
          "args": {
            "tenseal_context_file": "/path/to/my/client_context.tenseal"
          }
        }
      ]
    }
  ]
```

Thanks again for your help!

Regarding my business interest, my use case is about Vertical FL, i.e., multiple data parties with different data schemas. On top of that, I hope to adopt encryption techniques, e.g., HEModelEncryptor.

**Comment by YuanTingHsieh** [comment]
Thanks @shawndengucf for the detailed logs and information and your interest!

Reading from your logs, it looks like you did not configure HE related filters on the "server" side so it is complaining.

From the example you might need to configure: https://github.com/NVIDIA/NVFlare/blob/2.3.2/examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_he/cifar10_fedavg_he/config/config_fed_server.json#L25-L30

@holgerroth can help comment on the algorithm side for vertical FL with HE.

**Comment by holgerroth** [comment]
`CIFAR10LearnerSplitNN` uses the [aux message channel](https://github.com/NVIDIA/NVFlare/blob/f72431f7d719c2d32d193c35344323437036ebdc/examples/advanced/vertical_federated_learning/cifar10-splitnn/src/splitnn/cifar10_learner_splitnn.py#L211) to communicate. So, the HE wouldn't apply to these messages as they are only for task-based messages from (task_data_filters) & to (task_result_filters) the server. For using HE filters in split learning, we would need to use the new client task controllers (cc @yanchengnv), which is an upcoming feature or you need to build the encryption/decryption into the aux message handle functions. 

Regarding the decomposers, @nvidianz might be able to give further details. It should be using `CKKSVectorDecomposer`. Maybe we need to make sure the decomposer is registered on both client and server when using the simulator.

**Comment by shawndengucf** [comment]
Hi team. Sorry for the late reply. It's true that I didn't configure the HE filters on the server node correctly. With that fixed, now I get my Horizontal FL experiment run with HE. I may test HE against VFL with your future release.
I'd close this error for now. I sincerely appreciate your help!
