### ISSUE TITLE
Initialize the security_content_manager and SecurityContentService in simulator

### ISSUE THREAD

**Issue by holgerroth** [NVIDIA/NVFlare#1959]
This would help in experimenting with homomorphic encryption in simulation mode. Thanks @shawndengucf for raising the issue and providing a workaround.            

Thanks, @holgerroth ! It's really helpful. I created the `secure_workspace` and copied the whole folder to my project folder and specified the `tenseal_context_file` for `HEModelEncryptor`. However, the error persisted and I noticed that `SecurityContentService` doesn't get a chance to initial the `security_content_manager` if I submit the job with the simulator, see `load_tenseal_context_from_workspace` from `homomorphic_encrypt.py`.

I made it work by editing the function to below:
```
def load_tenseal_context_from_workspace(ctx_file_name: str, fl_ctx: FLContext):
    """Loads homomorphic encryption (HE) context from TenSEAL (https://github.com/OpenMined/TenSEAL) containing encryption keys and parameters.

    Args:
        ctx_file_name: filepath of TensSEAL context file
        fl_ctx: FL context

    Returns:
        TenSEAL context

    """
    is_secure_mode = fl_ctx.get_prop(FLContextKey.SECURE_MODE, True)
    if ctx_file_name != "client_context.tenseal":
        ssc = SecurityContentService()
        ssc.initialize(os.path.dirname(ctx_file_name))
        data, rc = ssc.load_content(ctx_file_name)
    else:
        data, rc = SecurityContentService.load_content(ctx_file_name)

    bad_rcs = [LoadResult.INVALID_CONTENT, LoadResult.NO_SUCH_CONTENT]
    if is_secure_mode:
        bad_rcs.extend([LoadResult.INVALID_SIGNATURE, LoadResult.NOT_SIGNED])

    if rc in bad_rcs:
        raise ValueError("Cannot load tenseal_context {}: {}".format(ctx_file_name, rc))

    context = ts.context_from(data)
    return context
```

With that error fixed, I bumped into the error below after the encryption:
```
-9972-4e44-af60-56a53c330eb2]: Encrypting vars 16 of 16: batchnorm2.num_batches_tracked with 1 values
2023-08-24 14:22:41,682 - HEModelEncryptor - INFO - [identity=site-1, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=2183f98a-9972-4e44-af60-56a53c330eb2]: Encryption time for 45891 of 45891 params (encrypted value range [-3.9569482803344727, 980.0]) 0.05233168601989746 seconds.
2023-08-24 14:22:41,683 - HEModelEncryptor - INFO - [identity=site-1, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=2183f98a-9972-4e44-af60-56a53c330eb2]: 16 of 16 layers encrypted
2023-08-24 14:22:41,683 - ClientRunner - INFO - [identity=site-1, run=simulate_job, peer=simulator_server, peer_run=simulate_job, task_name=train, task_id=2183f98a-9972-4e44-af60-56a53c330eb2]: finished processing task
2023-08-24 14:22:41,684 - FederatedClient - INFO - Starting to push execute result.
2023-08-24 14:22:41,888 - Cell - ERROR - [ME=server.simulate_job O=site-1.simulate_job D=server.simulate_job F=server T=server.simulate_job CH=server_command TP=submit_update] exception from CB execute_command: TypeError: Unknown type tenseal.tensors.ckksvector.CKKSVector, caused by mismatching decomposers
2023-08-24 14:22:41,888 - Cell - ERROR - Traceback (most recent call last):
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/fuel/f3/cellnet/cell.py", line 1437, in _try_cb
    return cb(message, *args, **kwargs)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/private/fed/server/server_command_agent.py", line 60, in execute_command
    data = fobs.loads(request.payload)
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/fuel/utils/fobs/fobs.py", line 249, in deserialize
    return msgpack.unpackb(data, object_hook=_fobs_unpacker, **kwargs)
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/Users/334997293/opt/anaconda3/envs/flare_he/lib/python3.9/site-packages/nvflare/fuel/utils/fobs/fobs.py", line 202, in _fobs_unpacker
    raise TypeError(f"Unknown type {type_name}, caused by mismatching decomposers")
TypeError: Unknown type tenseal.tensors.ckksvector.CKKSVector, caused by mismatching decomposers
```

I was wondering if you can share some ideas about how to solve it.

Below is the way I setup the HEModelEncryptor:
```
  "task_result_filters": [
    {
      "tasks": [
        "train"
      ],
      "filters": [
        {
          "name": "HEModelEncryptor",
          "args": {
            "weigh_by_local_iter": true,
            "tenseal_context_file": "/path/to/my/client_context.tenseal"
          }
        }
      ]
    },
    {
      "tasks": [
        "submit_model"
      ],
      "filters": [
        {
          "name": "HEModelEncryptor",
          "args": {
            "weigh_by_local_iter": false,
            "tenseal_context_file": "/path/to/my/client_context.tenseal"
          }
        }
      ]
    }
  ],
  "task_data_filters": [
    {
      "tasks": [
        "train",
        "validate"
      ],
      "filters": [
        {
          "name": "HEModelDecryptor",
          "args": {
            "tenseal_context_file": "/path/to/my/client_context.tenseal"
          }
        }
      ]
    }
  ]
```

Thanks again for your help!

Regarding my business interest, my use case is about Vertical FL, i.e., multiple data parties with different data schemas. On top of that, I hope to adopt encryption techniques, e.g., HEModelEncryptor.

_Originally posted by @shawndengucf in https://github.com/NVIDIA/NVFlare/issues/1924#issuecomment-1693472618_

**Comment by holgerroth** [comment]
@chesterxgchen , This issue is only about the secure content manager when running HE in simulation. The serialization error is discussed in this issue https://github.com/NVIDIA/NVFlare/issues/1924.

**Comment by holgerroth** [comment]
Note the related issue at https://github.com/NVIDIA/NVFlare/issues/1970

**Comment by YuanTingHsieh** [comment]
fixed by https://github.com/NVIDIA/NVFlare/pull/2631
and https://github.com/NVIDIA/NVFlare/pull/2339
