### ISSUE TITLE
Error using FedCE

### ISSUE THREAD

**Issue by 5wx** [NVIDIA/NVFlare#2132]
2023-11-07 10:36:21,234 - ScatterAndGather - ERROR - [identity=simulator_server, run=simulate_job, wf=scatter_and_gather, peer=site-2, peer_run=simulate_job, peer_rc=OK, task_name=train, task_id=4e7b6874-b2de-4566-a70b-06d56aa0188c]: processing error in result_received_cb on task train(4e7b6874-b2de-4566-a70b-06d56aa0188c): AttributeError: 'dict' object has no attribute 'data'
2023-11-07 10:36:21,235 - ScatterAndGather - ERROR - Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/fl1/lib/python3.8/site-packages/nvflare/apis/impl/controller.py", line 415, in _do_process_submission
    task.result_received_cb(client_task=client_task, fl_ctx=fl_ctx)
  File "/home/amax/anaconda3/envs/fl1/lib/python3.8/site-packages/nvflare/app_common/workflows/scatter_and_gather.py", line 318, in _process_train_result
    self._accept_train_result(client_name=client_name, result=result, fl_ctx=fl_ctx)
  File "/home/amax/anaconda3/envs/fl1/lib/python3.8/site-packages/nvflare/app_common/workflows/scatter_and_gather.py", line 356, in _accept_train_result
    accepted = self.aggregator.accept(result, fl_ctx)
  File "/home/amax/anaconda3/envs/fl1/lib/python3.8/site-packages/nvflare/app_common/aggregators/collect_and_assemble_aggregator.py", line 50, in accept
    return self._accept_contribution(contributor_name, current_round, data, fl_ctx)
  File "/home/amax/anaconda3/envs/fl1/lib/python3.8/site-packages/nvflare/app_common/aggregators/collect_and_assemble_aggregator.py", line 55, in _accept_contribution
    collection[contributor] = self.assembler.get_model_params(data)
  File "/amax/wx/FL/NVFlare-dev/workspace/fedce_prostate/simulate_job/app_site-1/custom/aggregators/fedce_assembler.py", line 73, in get_model_params
    data = dxo.data
AttributeError: 'dict' object has no attribute 'data'

**Comment by YuanTingHsieh** [comment]
@5wx thanks for your interest!
Can you provide some context so we know better?

What is your Python version?
What is your NVFlare version?
Do you use the branch that match the NVFlare version you installed?
What is your OS?
Have you tried run basic hello-numpy-sag example and see if it work?

What steps/command did you use to run this FedCE example?

**Comment by 5wx** [comment]
1. Python version: 3.8.18 
2. NVFlare version: 2.3.6
3. Branch: main
4. OS: linux
5. I have run basic hello-numpy-sag example and it works fine
6. Run command: nvflare simulator jobs/fedce_prostate -w /amax/NVFlare-dev/workspace/fedce_prostate -c site-1,site-2 -gpu 2,2

**Comment by 5wx** [comment]
> @5wx thanks for your interest! Can you provide some context so we know better?
> 
> What is your Python version? What is your NVFlare version? Do you use the branch that match the NVFlare version you installed? What is your OS? Have you tried run basic hello-numpy-sag example and see if it work?
> 
> What steps/command did you use to run this FedCE example?

1. Python version: 3.8.18 
2. NVFlare version: 2.3.6
3. Branch: main
4. OS: linux
5. I have run basic hello-numpy-sag example and it works fine
6. Run command: nvflare simulator jobs/fedce_prostate -w /amax/NVFlare-dev/workspace/fedce_prostate -c site-1,site-2 -gpu 2,2

**Comment by YuanTingHsieh** [comment]
@5wx thanks for the response!

I notice you are using NVFlare version 2.3.6 and branch main.
Those are NOT matched.

I would suggest you use **NVFlare version 2.3.8 AND branch 2.3**

Can you please try this combination?
