### ISSUE TITLE
Failed to bind to address of my server

### ISSUE THREAD

**Issue by KCC13** [NVIDIA/NVFlare#416]
Hi, I was trying to deploy a NVFlare server in a realistic network environment. After the provisioning, I ran the `start.sh` in the $SERVER_NAME folder to start the server but got the following error message (with GRPC_VERBOSITY=debug enabled):
```
start fl because of no pid.fl
new pid 33923
D0418 10:09:21.218743000 4753366464 ev_posix.cc:172]                   Using polling engine: poll
D0418 10:09:21.218819000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "grpclb"
D0418 10:09:21.218827000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "priority_experimental"
D0418 10:09:21.218833000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "weighted_target_experimental"
D0418 10:09:21.218838000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "pick_first"
D0418 10:09:21.218841000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "round_robin"
D0418 10:09:21.218845000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "ring_hash_experimental"
D0418 10:09:21.218850000 4753366464 dns_resolver_ares.cc:624]          Using ares dns resolver
D0418 10:09:21.218908000 4753366464 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0418 10:09:21.218913000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "cds_experimental"
D0418 10:09:21.218918000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "xds_cluster_impl_experimental"
D0418 10:09:21.218923000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "xds_cluster_resolver_experimental"
D0418 10:09:21.218927000 4753366464 lb_policy_registry.cc:42]          registering LB policy factory for "xds_cluster_manager_experimental"
E0418 10:09:21.393418000 4753366464 server_secure_chttp2.cc:120]       {"created":"@1650247761.393360000","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":936,"referenced_errors":[{"created":"@1650247761.393352000","description":"Unable to configure socket","fd":8,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":218,"referenced_errors":[{"created":"@1650247761.393339000","description":"Can't assign requested address","errno":49,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":191,"os_error":"Can't assign requested address","syscall":"bind"}]}]}
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/site-packages/nvflare/private/fed/app/server/server_train.py", line 256, in <module>
    main()
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/site-packages/nvflare/private/fed/app/server/server_train.py", line 94, in main
    services = deployer.deploy(args)
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/site-packages/nvflare/private/fed/app/trainers/server_deployer.py", line 96, in deploy
    services.deploy(grpc_args=first_server, secure_train=self.secure_train)
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/site-packages/nvflare/private/fed/server/fed_server.py", line 151, in deploy
    self.grpc_server.add_secure_port(target, server_credentials)
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/site-packages/grpc/_server.py", line 973, in add_secure_port
    return _common.validate_port_binding_result(
  File "/opt/anaconda3/envs/nvflare/lib/python3.8/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address xxxxx.asuscomm.com:18002; set GRPC_VERBOSITY=debug environment variable to see detailed error message.
```
My setting and environments:
- MacOS 10.15.7 & Ubuntu 20.04.4 LTS
- Python 3.8.12
- nvflare 2.0.16

Here is some information about my server:
- My server doesn't have a FQDN, so I use DDNS and virtual server services of ASUS router as an alternative.
- The DDNS is functioning properly, I am able to ping my server (xxxxx.asuscomm.com) from the external network.
- The port forwarding of port 18002 is enabled, and I've also confirmed that port 18002 was not used by any other applications.
- I've tried several different ports, but still no luck as of yet.

Any suggestion regarding this problem would be appreciated, thank you.

**Comment by yanchengnv** [comment]
I suspect that your server itself doesn't recognize xxxxx.asuscomm.com. You can verify that by pinging this address from your server.

Regardless, to make your server recognize this, the easiest way is perhaps to add it to /etc/hosts file and point it to localhost (127.0.0.1).

**Comment by KCC13** [comment]
Hi, thanks for the advice, the NVFlare server was successfully set up after adding `127.0.0.1 xxxxx.asuscomm.com` mapping to the `/etc/hosts`. However, my client site could not connect to the server from the external network. I think that's because this setting would make the server only listen to the local connections. So I replaced `127.0.0.1` with `0.0.0.0` in the mapping, and then everything worked as expected. Thanks for the help again, cheers.
